Revert "CI failure - version yields "2202-10-06""
This reverts commit 7887f2c6b114bd11c1b54e1adbd03bb32d7467a1.

formatting error

diff --git a/.github/workflows/3-test-docker.yml b/.github/workflows/3-test-docker.yml
--- a/.github/workflows/3-test-docker.yml
+++ b/.github/workflows/3-test-docker.yml
@@ -4,188 +4,191 @@ name: 🤖 Docker Tests
 on: workflow_call
 
 env:
-    DOCKER_BUILDKIT: 1
+  DOCKER_BUILDKIT: 1
 
 # TODO: Add independent job that builds the images.
 jobs:
-    docker-torch-unit:
-        name: ☁️ Pytorch Image Tests [Container]
-        runs-on: ubuntu-latest
-        steps:
-            - name: 🐄 Got git?
-              uses: actions/checkout@v3
-              with:
-                  fetch-depth: 0
+  docker-torch-unit:
+    name: ☁️ Pytorch Image Tests [Container]
+    runs-on: ubuntu-latest
+    steps:
+      - name: 🐄 Got git?
+        uses: actions/checkout@v3
+        with:
+          fetch-depth: 0
 
-            # Get history and tags for SCM versioning to work
-            # yamllint disable rule:indentation
-            - name: 📩 Checkout the Source
-              run: |
-                  git fetch --prune --unshallow || true
-                  git fetch --depth=1 origin +refs/tags/*:refs/tags/*
-                  # Verify .git folder
-                  if [ ! -d "./.git" ]; then
-                    echo "Expected ./.git folder to exist"
-                    exit 1
-                  fi
-            # yamllint enable rule:indentation
-            - name: 🐍 Switch Python 3.9
-              uses: actions/setup-python@v4
-              with:
-                  python-version: 3.9
+      # Get history and tags for SCM versioning to work
+      # yamllint disable rule:indentation
+      - name: 📩 Checkout the Source
+        run: |
+          git fetch --prune --unshallow || true
+          git fetch --depth=1 origin +refs/tags/*:refs/tags/*
+          # Verify .git folder
+          if [ ! -d "./.git" ]; then
+            echo "Expected ./.git folder to exist"
+            exit 1
+          fi
+      # yamllint enable rule:indentation
 
-            - name: 🌱 Setup Test Enviroment
-              run: |
-                  python -m pip install --upgrade pip
-                  python -m pip install --upgrade build
+      - name: 🐍 Switch Python 3.9
+        uses: actions/setup-python@v4
+        with:
+          python-version: 3.9
 
-            - name: ⚙️ Installing Armory
-              shell: bash
-              run: |
-                  pip install --no-compile --editable .
-                  armory configure --use-defaults
+      - name: 🌱 Setup Test Enviroment
+        run: |
+          python -m pip install --upgrade pip
+          python -m pip install --upgrade build
 
-            - name: 🚧 Build the Container
-              run: |
-                  python docker/build.py --framework pytorch
+      - name: ⚙️ Installing Armory
+        shell: bash
+        run: |
+          pip install --no-compile --editable .
+          armory configure --use-defaults
 
-            # TODO: Create/mount a volume with the tests and config files.
-            # yamllint disable rule:indentation
-            - name: 🤞 Run Image tests
-              run: |
-                  ARMORY_VERSION=`armory --version | sed -r 's/\+/\./g'`
-                  docker run                                  \
-                    --rm                                      \
-                    --workdir /armory-repo                    \
-                    twosixarmory/pytorch:${ARMORY_VERSION}    \
-                      pytest                                  \
-                        -c /armory-repo/pyproject.toml        \
-                        -m "not docker_required and unit"     \
-                        ./tests/
-            # TODO:
-            # - name: Dump docker logs on failure
-            #   if: failure()
-            #   uses: jwalton/gh-docker-logs@v1
-            # yamllint enable rule:indentation
+      - name: 🚧 Build the Container
+        run: |
+          python docker/build.py --framework pytorch
 
-    docker-tf2-unit:
-        name: ☁️ Docker TF2 Image Tests
-        runs-on: ubuntu-latest
-        steps:
-            - name: 🐄 Got git?
-              uses: actions/checkout@v3
-              with:
-                  fetch-depth: 0
+      # TODO: Create/mount a volume with the tests and config files.
+      # yamllint disable rule:indentation
+      - name: 🤞 Run Image tests
+        run: |
+          ARMORY_VERSION=`armory --version | sed -r 's/\+/\./g'`
+          docker run                                  \
+            --rm                                      \
+            --workdir /armory-repo                    \
+            twosixarmory/pytorch:${ARMORY_VERSION}    \
+              pytest                                  \
+                -c /armory-repo/pyproject.toml        \
+                -m "not docker_required and unit"     \
+                ./tests/
+      # TODO:
+      # - name: Dump docker logs on failure
+      #   if: failure()
+      #   uses: jwalton/gh-docker-logs@v1
+      # yamllint enable rule:indentation
 
-            # Get history and tags for SCM versioning to work
-            # yamllint disable rule:indentation
-            - name: 📩 Checkout the Source
-              run: |
-                  git fetch --prune --unshallow || true
-                  git fetch --depth=1 origin +refs/tags/*:refs/tags/*
-                  # Verify .git folder
-                  if [ ! -d "./.git" ]; then
-                    echo "Expected ./.git folder to exist"
-                    exit 1
-                  fi
-            # yamllint enable rule:indentation
-            - name: 🐍 Switch Python 3.9
-              uses: actions/setup-python@v4
-              with:
-                  python-version: 3.9
 
-            - name: 🌱 Setup Test Enviroment
-              run: |
-                  python -m pip install --upgrade pip
-                  python -m pip install --upgrade build
+  docker-tf2-unit:
+    name: ☁️ Docker TF2 Image Tests
+    runs-on: ubuntu-latest
+    steps:
+      - name: 🐄 Got git?
+        uses: actions/checkout@v3
+        with:
+          fetch-depth: 0
 
-            - name: ⚙️ Installing Armory
-              shell: bash
-              run: |
-                  pip install --no-compile --editable .
-                  armory configure --use-defaults
+      # Get history and tags for SCM versioning to work
+      # yamllint disable rule:indentation
+      - name: 📩 Checkout the Source
+        run: |
+          git fetch --prune --unshallow || true
+          git fetch --depth=1 origin +refs/tags/*:refs/tags/*
+          # Verify .git folder
+          if [ ! -d "./.git" ]; then
+            echo "Expected ./.git folder to exist"
+            exit 1
+          fi
+      # yamllint enable rule:indentation
 
-            - name: 🚧 Build the Container
-              run: |
-                  python docker/build.py --framework tf2
+      - name: 🐍 Switch Python 3.9
+        uses: actions/setup-python@v4
+        with:
+          python-version: 3.9
 
-            # yamllint disable rule:indentation
-            - name: 🤞 Run Image tests
-              run: |
-                  ARMORY_VERSION=`armory --version | sed -r 's/\+/\./g'`
-                  docker run                                  \
-                    --rm                                      \
-                    --workdir /armory-repo                    \
-                    twosixarmory/tf2:${ARMORY_VERSION}        \
-                      pytest                                  \
-                        -c /armory-repo/pyproject.toml        \
-                        -m "not docker_required and unit"     \
-                        ./tests/
-            # yamllint enable rule:indentation
+      - name: 🌱 Setup Test Enviroment
+        run: |
+          python -m pip install --upgrade pip
+          python -m pip install --upgrade build
 
-    docker-deepspeech-unit:
-        name: ☁️ Docker Deepspeech Image Tests
-        runs-on: ubuntu-latest
-        steps:
-            - name: 🐄 Got git?
-              uses: actions/checkout@v3
-              with:
-                  fetch-depth: 0
+      - name: ⚙️ Installing Armory
+        shell: bash
+        run: |
+          pip install --no-compile --editable .
+          armory configure --use-defaults
 
-            # TODO: this is redundant with actions/checkout@v3
-            # Get history and tags for SCM versioning to work
-            # yamllint disable rule:indentation
-            #   - name: 📩 Checkout the Source
-            #     run: |
-            #       git fetch --prune --unshallow || true
-            #       git fetch --depth=1 origin +refs/tags/*:refs/tags/*
-            #       # Verify .git folder
-            #       if [ ! -d "./.git" ]; then
-            #         echo "Expected ./.git folder to exist"
-            #         exit 1
-            #       fi
-            # yamllint enable rule:indentation
-            - name: 🐍 Switch Python 3.9
-              uses: actions/setup-python@v4
-              # TODO: what python do we get by default?
-              # with:
-              #   python-version: 3.9
+      - name: 🚧 Build the Container
+        run: |
+          python docker/build.py --framework tf2
 
-            - name: 🌱 Setup Test Enviroment
-              run: |
-                  python -m pip install --upgrade pip build
+      # yamllint disable rule:indentation
+      - name: 🤞 Run Image tests
+        run: |
+          ARMORY_VERSION=`armory --version | sed -r 's/\+/\./g'`
+          docker run                                  \
+            --rm                                      \
+            --workdir /armory-repo                    \
+            twosixarmory/tf2:${ARMORY_VERSION}        \
+              pytest                                  \
+                -c /armory-repo/pyproject.toml        \
+                -m "not docker_required and unit"     \
+                ./tests/
+      # yamllint enable rule:indentation
 
-            - name: ⚙️ Installing Armory
-              shell: bash
-              run: |
-                  pip install .
-                  armory configure --use-defaults
 
-            - name: 🚧 Build the Container
-              run: |
-                  python docker/build.py --framework pytorch-deepspeech
+  docker-deepspeech-unit:
+    name: ☁️ Docker Deepspeech Image Tests
+    runs-on: ubuntu-latest
+    steps:
+      - name: 🐄 Got git?
+        uses: actions/checkout@v3
+        with:
+          fetch-depth: 0
 
-            # yamllint disable rule:indentation
-            - name: 🤞 Run Image tests
-              run: |
-                  ARMORY_VERSION=`armory --version | sed -r 's/\+/\./g'`
-                  echo "docker friendly ARMORY_VERSION=${ARMORY_VERSION}"
+      # Get history and tags for SCM versioning to work
+      # yamllint disable rule:indentation
+      - name: 📩 Checkout the Source
+        run: |
+          git fetch --prune --unshallow || true
+          git fetch --depth=1 origin +refs/tags/*:refs/tags/*
+          # Verify .git folder
+          if [ ! -d "./.git" ]; then
+            echo "Expected ./.git folder to exist"
+            exit 1
+          fi
+      # yamllint enable rule:indentation
 
-                  docker run                                           \
-                    --rm                                               \
-                    --workdir /armory-repo                             \
-                    twosixarmory/pytorch-deepspeech:${ARMORY_VERSION}  \
-                      pytest                                           \
-                        -c /armory-repo/pyproject.toml                 \
-                        -m "not docker_required and unit"              \
-                        ./tests/
+      - name: 🐍 Switch Python 3.9
+        uses: actions/setup-python@v4
+        with:
+          python-version: 3.9
 
-                    docker run                                         \
-                    --rm                                               \
-                    --workdir /armory-repo                             \
-                    twosixarmory/pytorch-deepspeech:${ARMORY_VERSION}  \
-                      pytest                                           \
-                        -c /armory-repo/pyproject.toml                 \
-                        -m "pytorch_deepspeech"                        \
-                        ./tests/
-            # yamllint enable rule:indentation
+      - name: 🌱 Setup Test Enviroment
+        run: |
+          python -m pip install --upgrade pip
+          python -m pip install --upgrade build
+
+      - name: ⚙️ Installing Armory
+        shell: bash
+        run: |
+          pip install --no-compile --editable .
+          armory configure --use-defaults
+
+      - name: 🚧 Build the Container
+        run: |
+          python docker/build.py --framework pytorch-deepspeech
+
+      # yamllint disable rule:indentation
+      - name: 🤞 Run Image tests
+        run: |
+          ARMORY_VERSION=`armory --version | sed -r 's/\+/\./g'`
+
+          docker run                                           \
+            --rm                                               \
+            --workdir /armory-repo                             \
+            twosixarmory/pytorch-deepspeech:${ARMORY_VERSION}  \
+              pytest                                           \
+                -c /armory-repo/pyproject.toml                 \
+                -m "not docker_required and unit"              \
+                ./tests/
+
+            docker run                                         \
+            --rm                                               \
+            --workdir /armory-repo                             \
+            twosixarmory/pytorch-deepspeech:${ARMORY_VERSION}  \
+              pytest                                           \
+                -c /armory-repo/pyproject.toml                 \
+                -m "pytorch_deepspeech"                        \
+                ./tests/
+      # yamllint enable rule:indentation
