ci test

diff --git a/.github/workflows/ci_test.yml b/.github/workflows/ci_test.yml
--- a/.github/workflows/ci_test.yml
+++ b/.github/workflows/ci_test.yml
@@ -1,5 +1,5 @@
 ---
-name: CI Tests
+name: 🐛📦 CI Tests
 
 on:
   push:
@@ -30,8 +30,10 @@ jobs:
         python-version:
           - 3.9
     steps:
-      - name: 🌱 Setup Test Enviroment
+      - name: 🐍 Install Python ${{ matrix.python-version }}
         uses: actions/setup-python@v1
+
+      - name: 🌱 Setup Test Enviroment
         with:
           python-version: ${{ matrix.python-version }}
         run: |
@@ -39,14 +41,27 @@ jobs:
           python -m pip install --upgrade build
           pip install --no-compile --editable '.[developer]'
 
-      - name: 📩 Checkout the Source
+      - name: 🐄 Got git?
         uses: actions/checkout@v2
+
+        # Get history and tags for SCM versioning to work
+      - name: 📩 Checkout the Source
         run: |
           git fetch --prune --unshallow
           git fetch --depth=1 origin +refs/tags/*:refs/tags/*
 
       - name: Run commit hooks
-        run: bash tools/pre-commit.sh
+        run: >-
+          VERSION=`git describe --tags $(git rev-list --tags --max-count=1)`
+          echo "💄 Running pre-commit hooks for Armory version ${VERSION}"
+
+          bash tools/pre-commit.sh
+        # RESULT=$?
+        # if [ $RESULT -ne 0 ]; then
+        #   echo "🚨 Pre-commit hooks failed. Please run 'pre-commit run --all-files' locally to fix the issues 🚑"
+        #   exit 1
+        # fi
+
 
   # ----------- Bare Metal Tests -------------
   host-test:
@@ -64,16 +79,21 @@ jobs:
         - 3.9
         - 3.10
     steps:
-      - name: 🐍 Switch to Python v${{ matrix.python-version }}
+      - name: 🐍 Install Python ${{ matrix.python-version }}
         uses: actions/setup-python@v1
+
+      - name: 🐍 Switch to Python v${{ matrix.python-version }}
         with:
           python-version: ${{ matrix.python-version }}
         run: |
           python -m pip install --upgrade pip
           python -m pip install --upgrade build
 
-      - name: 📩 Checkout the Source
+      - name: 🐄 Got git?
         uses: actions/checkout@v2
+
+        # Get history and tags for SCM versioning to work
+      - name: 📩 Checkout the Source
         run: |
           git fetch --prune --unshallow
           git fetch --depth=1 origin +refs/tags/*:refs/tags/*
@@ -106,16 +126,21 @@ jobs:
         - 3.9
         - 3.10
     steps:
-      - name: 🐍 Switch to Python v${{ matrix.python-version }}
+      - name: 🐍 Install Python ${{ matrix.python-version }}
         uses: actions/setup-python@v1
+
+      - name: 🐍 Switch to Python v${{ matrix.python-version }}
         with:
           python-version: ${{ matrix.python-version }}
         run: |
           python -m pip install --upgrade pip
           python -m pip install --upgrade build
 
-      - name: 📩 Checkout the Source
+      - name: 🐄 Got git?
         uses: actions/checkout@v2
+
+        # Get history and tags for SCM versioning to work
+      - name: 📩 Checkout the Source
         run: |
           git fetch --prune --unshallow
           git fetch --depth=1 origin +refs/tags/*:refs/tags/*
@@ -148,16 +173,21 @@ jobs:
         - 3.9
         - 3.10
     steps:
-      - name: 🐍 Switch to Python v${{ matrix.python-version }}
+      - name: 🐍 Install Python ${{ matrix.python-version }}
         uses: actions/setup-python@v1
+
+      - name: 🐍 Switch to Python v${{ matrix.python-version }}
         with:
           python-version: ${{ matrix.python-version }}
         run: |
           python -m pip install --upgrade pip
           python -m pip install --upgrade build
 
-      - name: 📩 Checkout the Source
+      - name: 🐄 Got git?
         uses: actions/checkout@v2
+
+        # Get history and tags for SCM versioning to work
+      - name: 📩 Checkout the Source
         run: |
           git fetch --prune --unshallow
           git fetch --depth=1 origin +refs/tags/*:refs/tags/*
@@ -187,17 +217,28 @@ jobs:
         python-version:
           - 3.9
     steps:
-      - name: 🌱 Setup Test Enviroment
+      - name: 🐍 Install Python ${{ matrix.python-version }}
         uses: actions/setup-python@v1
+
+      - name: 🐍 Switch to Python v${{ matrix.python-version }}
         with:
           python-version: ${{ matrix.python-version }}
         run: |
           python -m pip install --upgrade pip
           python -m pip install --upgrade build
+
+      - name: 🌱 Setup Test Enviroment
+        uses: actions/setup-python@v1
+        with:
+          python-version: ${{ matrix.python-version }}
+        run: |
           pip install --no-compile --editable '.[developer]'
 
-      - name: 📩 Checkout the Source
+      - name: 🐄 Got git?
         uses: actions/checkout@v2
+
+        # Get history and tags for SCM versioning to work
+      - name: 📩 Checkout the Source
         run: |
           git fetch --prune --unshallow
           git fetch --depth=1 origin +refs/tags/*:refs/tags/*
@@ -212,6 +253,7 @@ jobs:
       - name: 🚧 Build the Container
         run: |
           python docker/build.py pytorch
+
       - name: 🤞 Run Unit tests
         run: |
           docker run -w /armory-repo/ twosixarmory/pytorch:$(armory --version) pytest -m "not docker_required and unit" ./tests/
@@ -258,5 +300,6 @@ jobs:
       #   run: python -m build
 
 # --------------------|---------------------
+#
 #
 # --------------------|---------------------
